name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install API dependencies
        run: |
          cd api
          npm ci
      
      - name: Build API
        run: |
          cd api
          npm run build
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_GLACIER_0813F2803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
        env:
          VITE_TRACKIMO_USERNAME: ${{ secrets.VITE_TRACKIMO_USERNAME }}
          VITE_TRACKIMO_PASSWORD: ${{ secrets.VITE_TRACKIMO_PASSWORD }}
          VITE_TRACKIMO_API_URL: ${{ secrets.VITE_TRACKIMO_API_URL }}
          VITE_TRACKIMO_CLIENT_ID: ${{ secrets.VITE_TRACKIMO_CLIENT_ID }}
          VITE_TRACKIMO_CLIENT_SECRET: ${{ secrets.VITE_TRACKIMO_CLIENT_SECRET }}
          VITE_TRACKIMO_REDIRECT_URI: ${{ secrets.VITE_TRACKIMO_REDIRECT_URI }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_GLACIER_0813F2803 }}
          action: "close"
